### ISSUE TITLE
feat: Add pre-commit.ci support

### ISSUE THREAD

**Issue by junghoon-vans** [junghoon-vans/checkstyle-cli#22]
Since `pre-commit.ci` cannot fetch at runtime, the following error occurs.
To solve this problem, the necessary files must be provided at package installation.

Error Log
---

```
checkstyle...............................................................Failed
- hook id: checkstyle
- exit code: 1

Traceback (most recent call last):
  File "/pc/clone/sag-ArCDSFu6R38Z1vpf4g/py_env-python3/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/pc/clone/sag-ArCDSFu6R38Z1vpf4g/py_env-python3/lib/python3.10/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/pc/clone/sag-ArCDSFu6R38Z1vpf4g/py_env-python3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/pc/clone/sag-ArCDSFu6R38Z1vpf4g/py_env-python3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/pc/clone/sag-ArCDSFu6R38Z1vpf4g/py_env-python3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/pc/clone/sag-ArCDSFu6R38Z1vpf4g/py_env-python3/lib/python3.10/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/pc/clone/sag-ArCDSFu6R38Z1vpf4g/py_env-python3/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7faf2c805180>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/pc/clone/sag-ArCDSFu6R38Z1vpf4g/py_env-python3/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/pc/clone/sag-ArCDSFu6R38Z1vpf4g/py_env-python3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/pc/clone/sag-ArCDSFu6R38Z1vpf4g/py_env-python3/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/checkstyle/checkstyle/releases/latest (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7faf2c805180>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/pc/clone/sag-ArCDSFu6R38Z1vpf4g/py_env-python3/bin/checkstyle", line 8, in <module>
    sys.exit(main())
  File "/pc/clone/sag-ArCDSFu6R38Z1vpf4g/py_env-python3/lib/python3.10/site-packages/checkstyle/cli.py", line 9, in main
    exit_code = app.run(argv)
  File "/pc/clone/sag-ArCDSFu6R38Z1vpf4g/py_env-python3/lib/python3.10/site-packages/checkstyle/application.py", line 20, in run
    filename = self._store.download_checkstyle(version)
  File "/pc/clone/sag-ArCDSFu6R38Z1vpf4g/py_env-python3/lib/python3.10/site-packages/checkstyle/utils/store.py", line 11, in download_checkstyle
    filename = self._get_checkstyle_filename(version)
  File "/pc/clone/sag-ArCDSFu6R38Z1vpf4g/py_env-python3/lib/python3.10/site-packages/checkstyle/utils/store.py", line 33, in _get_checkstyle_filename
    version = self._get_latest_checkstyle_version()
  File "/pc/clone/sag-ArCDSFu6R38Z1vpf4g/py_env-python3/lib/python3.10/site-packages/checkstyle/utils/store.py", line 39, in _get_latest_checkstyle_version
    response = requests.get(
  File "/pc/clone/sag-ArCDSFu6R38Z1vpf4g/py_env-python3/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/pc/clone/sag-ArCDSFu6R38Z1vpf4g/py_env-python3/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/pc/clone/sag-ArCDSFu6R38Z1vpf4g/py_env-python3/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/pc/clone/sag-ArCDSFu6R38Z1vpf4g/py_env-python3/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/pc/clone/sag-ArCDSFu6R38Z1vpf4g/py_env-python3/lib/python3.10/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/checkstyle/checkstyle/releases/latest (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7faf2c805180>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
©[ pre-commit.ci](https://results.pre-commit.ci/)  ·  [contact](mailto:info@pre-commit.ci)  ·  [security](mailto:security@pre-commit.ci)  ·  [privacy policy](https://pre-commit.ci/privacy_policy.html)  ·  [cookie notice](https://pre-commit.ci/cookie_notice.html)  ·  [issues](https://github.com/pre-commit-ci/issues)
```

**Comment by junghoon-vans** [comment]
`pre-commit` does not currently support `Java`. I will reopen it when it is supported later.
